name: Node.js Integration Test Action
description: Integration test on node.js source code
inputs:
  nodejs_version:
    type: string
    required: true
    description: Node.js version

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js ${{ inputs.nodejs_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodejs_version }}
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Run integration test
      run: npm run test int