name: Postman Installer
description: Postman CLI installer
inputs:
  postman-api-key:
    type: string
    required: true
    description: Postman API key

runs:
  using: composite
  steps:
    - name: Install Postman CLI
      run: |
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      shell: bash
    - name: Login to Postman CLI
      run: postman login --with-api-key ${{ inputs.postman-api-key }}
      shell: bash