name: Node.js Unit Test Action
description: Unit test on node.js source code
inputs:
  nodejs_version:
    type: string
    required: true
    description: Node.js version

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: kmhalpin/workflows/actions/nodejs@main
      with:
        nodejs_version: ${{ inputs.nodejs_version }}
    - name: Run unit test
      run: npm run test unit