name: Newman End To End Test Action
description: End to end test using newman
inputs:
  collection_path:
    type: string
    required: true
    description: Postman collection file path

runs:
  using: composite
  steps:
    - name: Run Newman        
      uses: docker://postman/newman:latest
      with:
        args: |
          run "${{ github.workspace }}/${{ inputs.collection_path }}" \
          --reporters cli,junit \
          --reporter-junit-export results.xml
    - name: Report Newman
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Postman end to end tests
        path: results.xml
        reporter: java-junit
        fail-on-error: true