name: Newman End To End Test Action
description: End to end test using newman
inputs:
  collection_path:
    type: string
    required: true
    description: Postman collection file path
  environment_path:
    type: string
    required: true
    description: Postman environment file path

runs:
  using: composite
  steps:
    - run: touch results.xml
      shell: bash
    - name: Install Newman
      run: npm install -g newman
      shell: bash
    - name: Run Newman        
      run: newman run "${{ inputs.collection_path }}" -e "${{ inputs.environment_path }}" --reporters cli,junit --reporter-junit-export results.xml
      shell: bash
    - name: Report Newman
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Postman end to end tests
        path: results.xml
        reporter: java-junit
        fail-on-error: true